### ISSUE TITLE
Advanced scheduling

### ISSUE THREAD

**Issue by mightyiam** [Hot6ix/WorldTimeAlarm#10]
Thank you for this app.

I'd like to have an alarm on the first and third Tuesdays of every month, on a specific time zone.

The time zone part seems to be covered. The advanced scheduling seems to not be.

Could you please develop that? I'd buy the app.

**Comment by Hot6ix** [comment]
Hello, Thank you for your opinion.
I will consider your opinion positively. But for now, i don't have time for taking care of my app. It might take some time. I will comment again when i'm ready.
Thank you.

**Comment by mightyiam** [comment]
Thank you for responding. I've found a solution by now so don't count on me, solely.
